CessChainConfig:
  # The rpc endpoint of the chain node
  Rpc:
    # test network
    - "wss://testnet-rpc.cess.cloud/ws"
    - "wss://testnet-rpc.cess.network/ws"
  # The storage network you want to connect to, "mainnet" or "testnet"
  Network: ""
  # CESS account mnemonic of cacher
  Mnemonic: "skill income exile ethics sick excess sea deliver medal junk update fault"

P2PConfig:
  # Bootstrap Nodes
  Boots:
    # test network
    - "_dnsaddr.boot-miner-testnet.cess.network"

  # Service workspace
  Workspace: "/"
  # P2P communication port
  P2PPort: 4006

CacherConfig:
  # User Files Cacher config
  # File cache size, default 512G, (unit is byte)
  CacheSize: 512
  # File cache expiration time, default 3*60 minutes (unit is minutes)
  Expiration:
  # Directory to store file cache, default path: Workspace/filecache/
  CacheDir:
  # Price of downloading a single fragment (unit is 1/10^18 CESS or TCESS, is an integer)
  CachePrice: ""
  # The number of free downloads allowed for users
  FreeDownloads:

CdnProtoConfig:
  # Cache protocol config
  # The Id of chain where the EVM contract is deployed
  ChainId: 11330
  # Ethereum gas free cap (default is 108694000460)
  GasFreeCap: 108694000460
  #Ethereum gas limit (default is 30000000)
  GasLimit: 30000000
  #Node staking amount
  Staking: "3000000000000000000000"
  #Protocol smart contracts for node registration, order and revenue management, etc.
  ContractAddresss:
    - "cache_protocol_contract": "0x7352188979857675C3aD1AA6662326ebD6DDBf6d"
    #Enter multiple values as a list of string key-value pairs
    #"cache_protocol_contract": "0xfA326Ce1E9D7d291B40945B6cDdCe8e9Efea9b34"
  # NFT Token Id that needs to be bound to the cache node(license for cache node to join network)
  NodeTokenId: "103025665189611818041125193990140224421208216751558425519579339636262984839876"
  # Cache Node's ethereum account private key (Hexadecimal string, not including '0x')
  NodeAccPrivateKey: "cdce8911cc893c792cd93508322e7d3dda9c6625fb5aea8f157668680491502e"
  #Token owner's ethereum account address (Hexadecimal string, including '0x')
  TokenAccAddress: "0xb7B43408864aEa0449D8F813380f8ec424F7a775"
  #The signature of the token owner's account on the message pair, obtained through the 'eth-tools'
  TokenAccSign: "12541b421928699836fae37df724648a395fe79a4c80adfdf8c58528d7ffc8106d5c13dcb616cf03098ce64dd588f997efa9de61d9520b1fec3e18064070c9381c"